// Restored from ref/.vite/build/mainView.js

export const localAgentModeSessionMethods = [
  "start",
  "sendMessage",
  "setModel",
  "setEffort",
  "setExtendedThinking",
  "setPermissionMode",
  "setChromePermissionMode",
  "noteCuWindowMentions",
  "stop",
  "stopTask",
  "rewind",
  "archive",
  "delete",
  "deleteBridgeSession",
  "deleteBridgeAgentMemory",
  "updateSession",
  "getSession",
  "getAll",
  "getTranscript",
  "searchSessions",
  "respondToToolPermission",
  "openOutputsDir",
  "shareSession",
  "submitTranscriptFeedback",
  "getTranscriptFeedback",
  "setDraftSessionFolders",
  "getDefaultWorkspaceFolders",
  "getSupportedCommands",
  "getTrustedFolders",
  "addTrustedFolder",
  "grantRemoteSessionFolders",
  "browseAndGrantRemoteSessionFolder",
  "grantRemoteSessionFolder",
  "clearRemoteSessionFolderGrants",
  "removeTrustedFolder",
  "isFolderTrusted",
  "addFolderToSession",
  "setMcpServers",
  "replaceRemoteMcpServers",
  "replaceEnabledMcpTools",
  "setFocusedSession",
  "signalSessionIntent",
  "syncSkills",
  "listLocalSkills",
  "getLocalSkillFiles",
  "saveLocalSkill",
  "setLocalSkillEnabled",
  "deleteLocalSkill",
  "revealLocalSkill",
  "respondDirectoryServers",
  "respondPluginSearch",
  "respondSlashMenuSkills",
  "mcpCallTool",
  "mcpReadResource",
  "mcpListResources",
  "mcpAuthenticate",
  "mcpReconnect",
  "mcpSubmitOAuthCallbackUrl",
  "getSessionsForScheduledTask",
  "resetBridge",
  "resetBridgeSession",
  "abandonBridgeEnvironment",
  "kickBridgePoll",
  "getBridgeConsent",
  "getSessionsBridgeEnabled",
  "setSessionsBridgeEnabled",
  "refetchMyAccess",
  "requestFolderTccAccess",
  "requestDocumentsTccAccess",
  "respondBridgePermissionPreflight",
  "startWatchRecording",
  "takeHeldWatchRecording",
  "releaseRemoteCuLock",
  "getAppIconForBundleId",
  "authorizeDirectMcpServer",
  "disconnectDirectMcpServer",
  "getDirectMcpServerStatuses",
  "directMcpCallTool",
  "directMcpReadResource",
  "directMcpListResources",
  "getManagedAskToolNames",
  "triggerInteractiveAuth",
  "revokeInteractiveAuth",
  "cancelInteractiveAuth",
] as const;

export type LocalAgentModeSessionMethod =
  (typeof localAgentModeSessionMethods)[number];

export const localAgentModeSessionEvents = [
  "onDirectMcpServerStatusesChanged",
  "onManagedAskToolNamesChanged",
  "onBridgePermissionPreflight",
  "onEvent",
  "onToolPermissionRequest",
  "onCoworkFromMain",
  "onRemoteSessionStart",
  "onCuEmergencyStop",
  "watchRecordingComplete",
] as const;
