// Restored from ref/webview/assets/app-initial~app-main~projects-index-page~local-conversation-page-4SURv8Cr.js
// Boundary facade for project hover card parts and remote connection rows.
import {
  $N as initVscodeApiBridge,
  $P as initAppScope,
  AB as initScopeRuntime,
  AV as initReactQueryRuntime,
  bF as initIntlMessageRuntime,
  bi as initButtonRuntime,
  cM as initModalRuntime,
  ci as initNotificationRuntime,
  Cx as getGlobalSettingValue,
  da as initLocalProjectActionsRuntime,
  DL as normalizeWorkspacePath,
  Ex as setGlobalSettingValue,
  FB as useScope,
  Gu as initCodexAppFrameRuntime,
  HE as useHostConfigById,
  HI as parseProjectWritableRoots,
  IB as useSignalValue,
  jM as initPersistentSignalRuntime,
  jr as threadAttentionCountsSignal,
  JV as initReactRuntime,
  KE as initKeyboardShortcutRuntime,
  kr as initClassNamesRuntime,
  Ku as useGlobalStateQuery,
  MM as createPersistentSignal,
  PB as useScopedValue,
  qE as useRemoteHostConfigs,
  qV as getChunkModuleExports,
  QP as appScope,
  qn as openLocalProjectEditModal,
  rF as defineMessages,
  si as ProjectAvatar,
  Sj as normalizeTextForCompare,
  tP as useAppServerMutation,
  Tx as initGlobalSettingsRuntime,
  ua as initPanelRuntime,
  uM as toastControllerSignal,
  Un as initSvgIconRuntime,
  VE as initGlobalStateQueryRuntime,
  VI as getProjectWritableRootsForDisplay,
  vi as updateWorkspaceRootLabel,
  wj as initStringNormalizeRuntime,
  XR as globalSettingKeys,
  yi as LocalProjectFallbackIcon,
  zV as useQueryClient,
  _i as initDialogRuntime,
} from "../vendor/appg-thread-shared-runtime";
import {
  classNames,
  FormattedMessage,
  GlobeIcon,
  initClassNameRuntime as initInlinePopoverRuntime,
  initGlobeIcon as initSignalHooksRuntime,
  initIntlRuntime as initReactIntlRuntime,
  initSettingsGearIcon as initWorkspaceRootLabelRuntime,
  initSpinnerComponent,
  SettingsGearIcon as EditProjectIcon,
  Spinner as ActivityIcon,
  useIntl,
} from "../boundaries/current-ref/appg-thread-shared-producer";
import {
  initRemoteConnectionStateChunk,
  initRemoteProjectIconChunk,
  initWaitingStatusIconChunk,
  RemoteProjectIcon,
  useRemoteConnectionState,
  WaitingStatusIcon,
} from "../remote/remote-connection-runtime";
import {
  Gd as initProfileIconsChunk,
  Wd as RowActionChevronIcon,
} from "../vendor/profile-page-runtime";

export {
  ActivityIcon,
  appScope,
  classNames,
  createPersistentSignal,
  defineMessages,
  EditProjectIcon,
  FormattedMessage,
  getChunkModuleExports,
  getGlobalSettingValue,
  getProjectWritableRootsForDisplay,
  globalSettingKeys,
  GlobeIcon,
  initAppScope,
  initButtonRuntime,
  initClassNamesRuntime,
  initCodexAppFrameRuntime,
  initDialogRuntime,
  initGlobalSettingsRuntime,
  initGlobalStateQueryRuntime,
  initInlinePopoverRuntime,
  initIntlMessageRuntime,
  initKeyboardShortcutRuntime,
  initLocalProjectActionsRuntime,
  initModalRuntime,
  initNotificationRuntime,
  initPanelRuntime,
  initPersistentSignalRuntime,
  initProfileIconsChunk,
  initReactIntlRuntime,
  initReactQueryRuntime,
  initReactRuntime,
  initRemoteProjectIconChunk as initRemoteConnectionActionsChunk,
  initRemoteConnectionStateChunk,
  initWaitingStatusIconChunk as initRemoteProjectIconChunk,
  initScopeRuntime,
  initSignalHooksRuntime,
  initSpinnerComponent,
  initStringNormalizeRuntime,
  initSvgIconRuntime,
  initVscodeApiBridge,
  initWorkspaceRootLabelRuntime,
  LocalProjectFallbackIcon,
  normalizeTextForCompare,
  normalizeWorkspacePath,
  openLocalProjectEditModal,
  parseProjectWritableRoots,
  ProjectAvatar,
  RemoteProjectIcon,
  RowActionChevronIcon,
  setGlobalSettingValue,
  threadAttentionCountsSignal,
  toastControllerSignal,
  updateWorkspaceRootLabel,
  useAppServerMutation,
  useGlobalStateQuery,
  useHostConfigById,
  useIntl,
  useQueryClient,
  useRemoteConnectionState,
  useRemoteHostConfigs,
  useScope,
  useScopedValue,
  useSignalValue,
  WaitingStatusIcon,
};
