// Restored from ref/webview/assets/app-initial~app-main~projects-index-page~local-conversation-page-4SURv8Cr.js
// Boundary facade for project hover card parts and remote connection rows.
import {
  $N as initVscodeApiBridge,
  $P as initAppScope,
  AB as initScopeRuntime,
  AN as initSpinnerComponent,
  AV as initReactQueryRuntime,
  BP as classNames,
  bF as initIntlMessageRuntime,
  bi as initButtonRuntime,
  cM as initModalRuntime,
  ci as initNotificationRuntime,
  Cx as getGlobalSettingValue,
  da as initLocalProjectActionsRuntime,
  DL as normalizeWorkspacePath,
  Ex as setGlobalSettingValue,
  FB as useScope,
  Gu as initCodexAppFrameRuntime,
  HE as useHostConfigById,
  HI as parseProjectWritableRoots,
  Hi as initWorkspaceRootLabelRuntime,
  iF as initReactIntlRuntime,
  IB as useSignalValue,
  jM as initPersistentSignalRuntime,
  jr as threadAttentionCountsSignal,
  JV as initReactRuntime,
  KE as initKeyboardShortcutRuntime,
  kN as ActivityIcon,
  kr as initClassNamesRuntime,
  Ku as useGlobalStateQuery,
  lF as useIntl,
  MM as createPersistentSignal,
  na as GlobeIcon,
  PB as useScopedValue,
  qE as useRemoteHostConfigs,
  qV as getChunkModuleExports,
  QP as appScope,
  qn as openLocalProjectEditModal,
  rF as defineMessages,
  ra as initSignalHooksRuntime,
  sF as FormattedMessage,
  si as ProjectAvatar,
  Sj as normalizeTextForCompare,
  tP as useAppServerMutation,
  Tx as initGlobalSettingsRuntime,
  ua as initPanelRuntime,
  uM as toastControllerSignal,
  Un as initSvgIconRuntime,
  VE as initGlobalStateQueryRuntime,
  VI as getProjectWritableRootsForDisplay,
  Vi as EditProjectIcon,
  vi as updateWorkspaceRootLabel,
  VP as initInlinePopoverRuntime,
  wj as initStringNormalizeRuntime,
  XR as globalSettingKeys,
  yi as LocalProjectFallbackIcon,
  zV as useQueryClient,
  _i as initDialogRuntime,
} from "../boundaries/current-ref/appg-thread-shared-producer";
import {
  an as useRemoteConnectionState,
  in as initRemoteConnectionStateChunk,
  nn as RemoteProjectIcon,
  oi as WaitingStatusIcon,
  rn as initRemoteConnectionActionsChunk,
  si as initRemoteProjectIconChunk,
} from "../boundaries/current-ref/appgen-library-hot-producer";
import {
  Gd as initProfileIconsChunk,
  Wd as RowActionChevronIcon,
} from "../boundaries/current-ref/profile-page-producer";

export {
  ActivityIcon,
  appScope,
  classNames,
  createPersistentSignal,
  defineMessages,
  EditProjectIcon,
  FormattedMessage,
  getChunkModuleExports,
  getGlobalSettingValue,
  getProjectWritableRootsForDisplay,
  globalSettingKeys,
  GlobeIcon,
  initAppScope,
  initButtonRuntime,
  initClassNamesRuntime,
  initCodexAppFrameRuntime,
  initDialogRuntime,
  initGlobalSettingsRuntime,
  initGlobalStateQueryRuntime,
  initInlinePopoverRuntime,
  initIntlMessageRuntime,
  initKeyboardShortcutRuntime,
  initLocalProjectActionsRuntime,
  initModalRuntime,
  initNotificationRuntime,
  initPanelRuntime,
  initPersistentSignalRuntime,
  initProfileIconsChunk,
  initReactIntlRuntime,
  initReactQueryRuntime,
  initReactRuntime,
  initRemoteConnectionActionsChunk,
  initRemoteConnectionStateChunk,
  initRemoteProjectIconChunk,
  initScopeRuntime,
  initSignalHooksRuntime,
  initSpinnerComponent,
  initStringNormalizeRuntime,
  initSvgIconRuntime,
  initVscodeApiBridge,
  initWorkspaceRootLabelRuntime,
  LocalProjectFallbackIcon,
  normalizeTextForCompare,
  normalizeWorkspacePath,
  openLocalProjectEditModal,
  parseProjectWritableRoots,
  ProjectAvatar,
  RemoteProjectIcon,
  RowActionChevronIcon,
  setGlobalSettingValue,
  threadAttentionCountsSignal,
  toastControllerSignal,
  updateWorkspaceRootLabel,
  useAppServerMutation,
  useGlobalStateQuery,
  useHostConfigById,
  useIntl,
  useQueryClient,
  useRemoteConnectionState,
  useRemoteHostConfigs,
  useScope,
  useScopedValue,
  useSignalValue,
  WaitingStatusIcon,
};
