// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~appgen-settings-page~appgen-publication-terms-ro~g0k1g2bt-B6jrUW_u.js
// Compatibility export map for the appgen settings/publication runtime.
export {
  initAppgenSettingsFilesystemMediaChunk as _,
  createOfficeAliasMentionItem as a,
  AppgenSettingsPublicationIcon as A,
  AppgenSettingsChromeIcon as b,
  findAppgenPluginForMention as c,
  initAppgenSettingsOpenAiIconChunk as C,
  createAppgenPluginMentionItem as d,
  initPrimaryRuntimeOfficePluginConstantsChunk as D,
  PRESENTATIONS_PLUGIN_NAME as E,
  initAppgenSettingsPublicationRuntimeChunk as f,
  getAppgenSettingsFilesystemMediaPath as g,
  getAppgenSettingsFilesystemMediaSrc as h,
  resolveMentionedOfficeAliasLabel as i,
  initAppgenSettingsPublicationIconChunk as j,
  isPresentationPlugin as k,
  getAppgenPluginDescription as l,
  initAppgenSettingsPluginIconChunk as m,
  AppgenPublicationTermsFallbackIcon as M,
  MICROSOFT_POWERPOINT_ALIAS as n,
  initAppgenPublicationTermsFallbackIconChunk as N,
  initOfficeNativeAppAliasChunk as o,
  isSpreadsheetPlugin as O,
  getAppgenSettingsPluginIcon as p,
  officeAliasMatchesQuery as r,
  nativeAppMatchesOfficeAlias as s,
  AppgenSettingsOpenAiIcon as S,
  MICROSOFT_EXCEL_ALIAS as t,
  APPGEN_SETTINGS_PUBLICATION_GATE_ID as T,
  getAppgenPluginMentionIcon as u,
  AppgenSettingsPencilIcon as v,
  SPREADSHEETS_PLUGIN_NAME as w,
  initAppgenSettingsChromeIconChunk as x,
  initAppgenSettingsPencilIconChunk as y,
} from "../../appgen/settings-publication-runtime";
