// Stub for plugin-detail-page-current to unblock plugin-detail-page-current-runtime promotion.
// @ts-nocheck

const slot = undefined as never;
const fn = () => {};

export const A = slot;
export const B = slot;
export const C = slot;
export const D = slot;
export const E = slot;
export const F = slot;
export const I = slot;
export const L = slot;
export const M = slot;
export const N = fn;
export const O = slot;
export const P = slot;
export const R = slot;
export const S = slot;
export const T = slot;
export const _ = slot;
export const _t = slot;
export const a = slot;
export const b = slot;
export const c = slot;
export const d = slot;
export const dt = slot;
export const f = slot;
export const ft = slot;
export const g = slot;
export const gt = slot;
export const h = slot;
export const ht = slot;
export const i = slot;
export const j = slot;
export const k = slot;
export const l = slot;
export const lt = slot;
export const m = slot;
export const mt = slot;
export const n = fn;
export const o = slot;
export const ot = slot;
export const p = slot;
export const pt = slot;
export const r = slot;
export const s = slot;
export const st = slot;
export const t = () => null;
export const u = slot;
export const ut = slot;
export const v = slot;
export const vt = slot;
export const w = slot;
export const x = slot;
export const y = slot;
export const yt = slot;
export const z = slot;
