// Restored from ref/webview/assets/thread-context-inputs-B6tQCr7t.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 300 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  _appScopeC as createComputedSignal,
  _appScopeG as createSignal,
  appScopeRoot,
  appScopeUnderscore,
} from "./app-scope";

const LOCAL_APP_SERVER_HOST_ID = "local";

export const $: any = undefined as any;
export const $n: any = undefined as any;
export const $r: any = undefined as any;
export const $t: any = undefined as any;
export const A: any = undefined as any;
export const Aa: any = undefined as any;
export const Ai: any = undefined as any;
export const An: any = undefined as any;
export const Ar: any = undefined as any;
export const At: any = undefined as any;
export const B: any = undefined as any;
export const Bi: any = undefined as any;
export const Bn: any = undefined as any;
export const Br: any = undefined as any;
export const Bt: any = undefined as any;
export const Ca: any = undefined as any;
export const Ci: any = undefined as any;
export const Cn: any = undefined as any;
export const Cr: any = undefined as any;
export const Ct: any = undefined as any;
export const D: any = undefined as any;
export const Da: any = undefined as any;
export const Di: any = undefined as any;
export const Dn: any = undefined as any;
export const Dr: any = undefined as any;
export const Dt: any = undefined as any;
export const E: any = undefined as any;
export const Ea: any = undefined as any;
export const Ei: any = undefined as any;
export const En: any = undefined as any;
export const Er: any = undefined as any;
export const browserUseEnabledForConversationSignal: any = undefined as any;
export const Et: any = undefined as any;
export const F: any = undefined as any;
export const Fi: any = undefined as any;
export const Fn: any = undefined as any;
export const Fr: any = undefined as any;
export const Ft: any = undefined as any;
export const G: any = undefined as any;
export const Gi: any = undefined as any;
export const Gn: any = undefined as any;
export const Gr: any = undefined as any;
export const Gt: any = undefined as any;
export const Hi: any = undefined as any;
export const Hn: any = undefined as any;
export const Hr: any = undefined as any;
export const CHROME_NATIVE_APP_DISPLAY_NAME: any = undefined as any;
export const Ht: any = undefined as any;
export const I: any = undefined as any;
export const Ii: any = undefined as any;
export const In: any = undefined as any;
export const Ir: any = undefined as any;
export const It: any = undefined as any;
export const J: any = undefined as any;
export const Ji: any = undefined as any;
export const Jn: any = undefined as any;
export const Jr: any = undefined as any;
export const Jt: any = undefined as any;
export const K: any = undefined as any;
export const Ki: any = undefined as any;
export const Kn: any = undefined as any;
export const Kr: any = undefined as any;
export const Kt: any = undefined as any;
export const L: any = undefined as any;
export const Li: any = undefined as any;
export const Ln: any = undefined as any;
export const Lr: any = undefined as any;
export const Lt: any = undefined as any;
export const Mi: any = undefined as any;
export const Mn: any = undefined as any;
export const Mr: any = undefined as any;
export const Mt: any = undefined as any;
export const N: any = undefined as any;
export const Ni: any = undefined as any;
export const Nn: any = undefined as any;
export const Nr: any = undefined as any;
export const Nt: any = undefined as any;
export const O: any = undefined as any;
export const Oa: any = undefined as any;
export const Oi: any = undefined as any;
export const On: any = undefined as any;
export const Or: any = undefined as any;
export const Ot: any = undefined as any;
export const P: any = undefined as any;
export const Pi: any = undefined as any;
export const Pn: any = undefined as any;
export const Pr: any = undefined as any;
export const Pt: any = undefined as any;
export const Q: any = undefined as any;
export const Qn: any = undefined as any;
export const Qr: any = undefined as any;
export const Qt: any = undefined as any;
export const R: any = undefined as any;
export const Ri: any = undefined as any;
export const Rn: any = undefined as any;
export const Rr: any = undefined as any;
export const Rt: any = undefined as any;
export const S: any = undefined as any;
export const Sa: any = undefined as any;
export const Si: any = undefined as any;
export const Sn: any = undefined as any;
export const Sr: any = undefined as any;
export const St: any = undefined as any;
export const T: any = undefined as any;
export const Ti: any = undefined as any;
export const Tn: any = undefined as any;
export const Tr: any = undefined as any;
export const Tt: any = undefined as any;
export const U: any = undefined as any;
export const Ui: any = undefined as any;
export const Un: any = undefined as any;
export const Ur: any = undefined as any;
export const isChromeNativeApp: any = undefined as any;
export const Ut: any = undefined as any;
export const V: any = undefined as any;
export const Vi: any = undefined as any;
export const Vn: any = undefined as any;
export const Vr: any = undefined as any;
export const Vt: any = undefined as any;
export const W: any = undefined as any;
export const Wi: any = undefined as any;
export const Wn: any = undefined as any;
export const Wr: any = undefined as any;
export const Wt: any = undefined as any;
export const X: any = undefined as any;
export const Xi: any = undefined as any;
export const Xn: any = undefined as any;
export const Xr: any = undefined as any;
export const Xt: any = undefined as any;
export const Y: any = undefined as any;
export const Yi: any = undefined as any;
export const Yn: any = undefined as any;
export const Yr: any = undefined as any;
export const Yt: any = undefined as any;
export const Z: any = undefined as any;
export const Zi: any = undefined as any;
export const Zn: any = undefined as any;
export const Zr: any = undefined as any;
export const Zt: any = undefined as any;
export const _a: any = undefined as any;
export const _i: any = undefined as any;
export const _n: any = undefined as any;
export const _r: any = undefined as any;
export const _t: any = undefined as any;
export const a: any = undefined as any;
export const aa: any = undefined as any;
export const ai: any = undefined as any;
export const an: any = undefined as any;
export const ar: any = undefined as any;
export const at: any = undefined as any;
export const ba: any = undefined as any;
export const bi: any = undefined as any;
export const bn: any = undefined as any;
export const br: any = undefined as any;
export const bt: any = undefined as any;
export const ca: any = undefined as any;
export const ci: any = undefined as any;
export const cn: any = undefined as any;
export const cr: any = undefined as any;
export const ct: any = undefined as any;
export const d: any = undefined as any;
export const da: any = undefined as any;
export const di: any = undefined as any;
export const dr: any = undefined as any;
export const dt: any = undefined as any;
export const ei: any = undefined as any;
export const en: any = undefined as any;
export const er: any = undefined as any;
export const et: any = undefined as any;
export const f: any = undefined as any;
export const fa: any = undefined as any;
export const fi: any = undefined as any;
export const fn: any = undefined as any;
export const fr: any = undefined as any;
export const ft: any = undefined as any;
export const g: any = undefined as any;
export const ga: any = undefined as any;
export const gi: any = undefined as any;
export const gn: any = undefined as any;
export const gr: any = undefined as any;
export const ha: any = undefined as any;
export const hi: any = undefined as any;
export const hn: any = undefined as any;
export const hr: any = undefined as any;
export const ht: any = undefined as any;
export const i: any = undefined as any;
export const ia: any = undefined as any;
export const ii: any = undefined as any;
const in_: any = undefined as any;
export { in_ as in };
export const ir: any = undefined as any;
export const it: any = undefined as any;
export const ji: any = undefined as any;
export const jn: any = undefined as any;
export const jr: any = undefined as any;
export const jt: any = undefined as any;
export const k: any = undefined as any;
export const ka: any = undefined as any;
export const ki: any = undefined as any;
export const kn: any = undefined as any;
export const kr: any = undefined as any;
export const kt: any = undefined as any;
export const l: any = undefined as any;
export const la: any = undefined as any;
export const li: any = undefined as any;
export const ln: any = undefined as any;
export const lr: any = undefined as any;
export const lt: any = undefined as any;
export const ma: any = undefined as any;
export const mi: any = undefined as any;
export const mn: any = undefined as any;
export const mr: any = undefined as any;
export const mt: any = undefined as any;
export const na: any = undefined as any;
export const ni: any = undefined as any;
export const nn: any = undefined as any;
export const nr: any = undefined as any;
export const nt: any = undefined as any;
export const o: any = undefined as any;
export const oa: any = undefined as any;
export const oi: any = undefined as any;
export const on: any = undefined as any;
export const or: any = undefined as any;
export const ot: any = undefined as any;
export const pa: any = undefined as any;
export const pi: any = undefined as any;
export const pr: any = undefined as any;
export const pt: any = undefined as any;
export const q: any = undefined as any;
export const qi: any = undefined as any;
export const qn: any = undefined as any;
export const qr: any = undefined as any;
export const qt: any = undefined as any;
export const r: any = undefined as any;
export const ra: any = undefined as any;
export const ri: any = undefined as any;
export const rn: any = undefined as any;
export const rr: any = undefined as any;
export const rt: any = undefined as any;
export const sa: any = undefined as any;
export const si: any = undefined as any;
export const sn: any = undefined as any;
export const sr: any = undefined as any;
export const st: any = undefined as any;
export const t: any = undefined as any;
export const ti: any = undefined as any;
export const tn: any = undefined as any;
export const tr: any = undefined as any;
export const tt: any = undefined as any;
export const u: any = undefined as any;
export const ua: any = undefined as any;
export const ui: any = undefined as any;
export const un: any = undefined as any;
export const ur: any = undefined as any;
export const ut: any = undefined as any;
export const va: any = undefined as any;
export const vi: any = undefined as any;
export const vn: any = undefined as any;
export const vr: any = undefined as any;
export const vt: any = undefined as any;
export const w: any = undefined as any;
export const wa: any = undefined as any;
export const wi: any = undefined as any;
export const wn: any = undefined as any;
export const wr: any = undefined as any;
export const x: any = undefined as any;
export const xa: any = undefined as any;
export const xi: any = undefined as any;
export const xn: any = undefined as any;
export const xr: any = undefined as any;
export const xt: any = undefined as any;
export const ya: any = undefined as any;
export const yi: any = undefined as any;
export const yn: any = undefined as any;
export const yr: any = undefined as any;
export const yt: any = undefined as any;
export const z: any = undefined as any;
export const zi: any = undefined as any;
export const zn: any = undefined as any;
export const zr: any = undefined as any;
export const zt: any = undefined as any;

export function applyRemoteControlHostStatus(
  scope: AppScopeStoreLike,
  hostId: string,
  status: unknown,
): void {
  scope.set(remoteControlConnectionStatusSignal, hostId, status);
}
export const codexHomeQuery: any = undefined as any;
export const conversationPermissionConfigSignal: any = undefined as any;
export const conversationTitleSignal: any = undefined as any;
export const conversationTurnsSignal: any = undefined as any;
export const conversationVisibleTurnsSignal: any = undefined as any;
export const latestTurnByConversationIdSignal: any = undefined as any;
export const linkedConversationIdSignal: any = undefined as any;
export const remoteControlConnectionStatusSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const selectedHostIdSignal = createSignal(
  appScopeRoot,
  LOCAL_APP_SERVER_HOST_ID,
);
export {
  selectedHostIdSignal as M,
  remoteControlConnectionStatusSignal as dn,
  applyRemoteControlHostStatus as pn,
};
export const globalStateSignal = appScopeUnderscore(
  "global-state",
  () => undefined,
);
export { globalStateSignal as ea };
export const $i = globalStateSignal;
export const c = appScopeUnderscore("remote-projects", () => []);
export const s = appScopeUnderscore("remote-host-configs", () => []);
export const n = appScopeUnderscore("active-workspace-roots", () => ({
  roots: [],
}));
export function ta(store: any, key: string, value: unknown): void {
  store?.query?.setData?.(globalStateSignal, key, { value });
}
export const homeDirectoryQuery: any = undefined as any;
export const createGitQueryOptions: any = undefined as any;
export const disabledGitQueryResult: any = undefined as any;
export const gitRepositoryWatcherSignal: any = undefined as any;
export const gitStableMetadataQuery: any = undefined as any;
export const normalizeHostConfigForWorktreeKey: any = undefined as any;
export const pendingGitQueryResult: any = undefined as any;
export const resolveGitQueryOptions: any = undefined as any;
export const serviceClientForHost: any = undefined as any;
export const trackOnboardingWizardAction: any = undefined as any;
export const useGitRepositoryQuery: any = undefined as any;
type AppScopeStoreLike = {
  get<TValue = unknown>(signal: unknown, ...args: unknown[]): TValue;
  set(signal: unknown, ...args: unknown[]): void;
};
type AppServerConnectionUpdate = {
  appServerVersion?: unknown;
  error?: unknown;
  hostId: string;
  installedCodexVersion?: unknown;
  source?: string;
  state: unknown;
};

export const appServerConnectionErrorSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const appServerConnectionStateSignal = appScopeUnderscore(
  appScopeRoot,
  () => "disconnected",
);
export const appServerConnectionManagerSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const appServerVersionSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const installedCodexVersionSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const hostManagerStoreSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const conversationAppServerManagerOverrideSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const registeredAppServerHostIdsSignal = createSignal(
  appScopeRoot,
  [] as string[],
);
export const appServerRegistryVersionSignal = createSignal(appScopeRoot, 0);
export const allAppServerManagersSignal = createComputedSignal(
  appScopeRoot,
  ({
    get,
  }: {
    get: <TValue = unknown>(signal: unknown, key?: unknown) => TValue;
  }) =>
    (get<string[]>(registeredAppServerHostIdsSignal) ?? [])
      .map((hostId) => get(appServerConnectionManagerSignal, hostId))
      .filter(Boolean),
);
export const defaultAppServerManagerSignal = createComputedSignal(
  appScopeRoot,
  ({
    get,
  }: {
    get: <TValue = unknown>(signal: unknown, key?: unknown) => TValue;
  }) =>
    get(appServerConnectionManagerSignal, LOCAL_APP_SERVER_HOST_ID) ??
    (get<unknown[]>(allAppServerManagersSignal) ?? [])[0] ??
    null,
);
export function getAppServerConnectionStateForHost(
  scope: AppScopeStoreLike,
  hostId: string,
): {
  appServerVersion: unknown;
  error: any;
  installedCodexVersion: unknown;
  state: any;
} {
  return {
    appServerVersion: scope.get(appServerVersionSignal, hostId),
    error: scope.get(appServerConnectionErrorSignal, hostId),
    installedCodexVersion: scope.get(installedCodexVersionSignal, hostId),
    state: scope.get(appServerConnectionStateSignal, hostId),
  };
}
export function getAppServerManagerForConversationId(
  scope: AppScopeStoreLike,
  conversationId: string,
): unknown {
  return (
    scope.get(conversationAppServerManagerOverrideSignal, conversationId) ??
    scope.get(defaultAppServerManagerSignal)
  );
}
export function setAppServerConnectionState(
  scope: AppScopeStoreLike,
  update: AppServerConnectionUpdate,
): void {
  scope.set(appServerConnectionStateSignal, update.hostId, update.state);
  scope.set(
    appServerConnectionErrorSignal,
    update.hostId,
    update.error ?? null,
  );
  if ("appServerVersion" in update) {
    scope.set(appServerVersionSignal, update.hostId, update.appServerVersion);
  }
  if ("installedCodexVersion" in update) {
    scope.set(
      installedCodexVersionSignal,
      update.hostId,
      update.installedCodexVersion,
    );
  }
}
export function wrapAppServerManager<TManager>(manager: TManager): TManager {
  return manager;
}
export {
  appServerVersionSignal as C,
  installedCodexVersionSignal as H,
  wrapAppServerManager as Ta,
  conversationAppServerManagerOverrideSignal as _,
  appServerRegistryVersionSignal as b,
  registeredAppServerHostIdsSignal as gt,
  hostManagerStoreSignal as h,
  defaultAppServerManagerSignal as j,
  appServerConnectionStateSignal as m,
  appServerConnectionErrorSignal as p,
  appServerConnectionManagerSignal as v,
  setAppServerConnectionState as wt,
  allAppServerManagersSignal as y,
};
export const parseSkillPathMetadata: any = undefined as any;
export const conversationHostIdByConversationIdSignal: any = undefined as any;
export const latestCollaborationModeByConversationIdSignal: any =
  undefined as any;
export const localThreadSummaryByConversationIdSignal: any = undefined as any;
export const mcpLoginResultSignal: any = undefined as any;
export function getGlobalStateValue(
  get: (signal: unknown, key: string) => unknown,
  key: string,
  fallbackValue?: unknown,
): unknown {
  const storedValue = get(globalStateSignal, key);
  if (
    storedValue != null &&
    typeof storedValue === "object" &&
    "value" in storedValue
  ) {
    return (storedValue as { value: unknown }).value;
  }
  return storedValue ?? fallbackValue;
}
export { getGlobalStateValue as Qi };
export const useGitMetadataQuery: any = undefined as any;
export const workspaceRootOptionsQuery: any = undefined as any;
export const workspaceRootOptionsQueryForHost: any = undefined as any;
export const produceImmutableUpdate: any = undefined as any;
export const formatDebugParamsPreview: any = undefined as any;
export const applyActiveProfileConfigOverrides: any = undefined as any;
export const resolveRequestServiceTier: any = undefined as any;
export const resolveServiceTierPreferenceValue: any = undefined as any;
export const serviceTierPreferenceSignal: any = undefined as any;
