// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~appgen-settings-page~appgen-publication-terms-ro~g0k1g2bt-B6jrUW_u.js
// Semantic alias layer for appgen settings/publication runtime.
export {
  _ as initAppgenSettingsFilesystemMediaChunk,
  a as createOfficeAliasMentionItem,
  A as AppgenSettingsPublicationIcon,
  b as AppgenSettingsChromeIcon,
  c as findAppgenPluginForMention,
  C as initAppgenSettingsOpenAiIconChunk,
  d as createAppgenPluginMentionItem,
  D as initPrimaryRuntimeOfficePluginConstantsChunk,
  E as PRESENTATIONS_PLUGIN_NAME,
  f as initAppgenSettingsPublicationRuntimeChunk,
  g as getAppgenSettingsFilesystemMediaPath,
  h as getAppgenSettingsFilesystemMediaSrc,
  i as resolveMentionedOfficeAliasLabel,
  j as initAppgenSettingsPublicationIconChunk,
  k as isPresentationPlugin,
  l as getAppgenPluginDescription,
  m as initAppgenSettingsPluginIconChunk,
  M as AppgenPublicationTermsFallbackIcon,
  n as MICROSOFT_POWERPOINT_ALIAS,
  N as initAppgenPublicationTermsFallbackIconChunk,
  o as initOfficeNativeAppAliasChunk,
  O as isSpreadsheetPlugin,
  p as getAppgenSettingsPluginIcon,
  r as officeAliasMatchesQuery,
  s as nativeAppMatchesOfficeAlias,
  S as AppgenSettingsOpenAiIcon,
  t as MICROSOFT_EXCEL_ALIAS,
  T as APPGEN_SETTINGS_PUBLICATION_GATE_ID,
  u as getAppgenPluginMentionIcon,
  v as AppgenSettingsPencilIcon,
  w as SPREADSHEETS_PLUGIN_NAME,
  x as initAppgenSettingsChromeIconChunk,
  y as initAppgenSettingsPencilIconChunk,
} from "../../boundaries/current-ref/current-app-initial-appgen-settings-publication-runtime-producer";
