// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~remote-conversation-page~pull-requests-page~new-~ozr5a6hk-DZC70s11.js
// Semantic alias layer for pull request new-thread runtime.
// prettier-ignore
export {
  _ as pullRequestNewThreadCompatSlotUnderscore, _n as pullRequestNewThreadCompatSlotUnderscoreLowerN, _t as pullRequestNewThreadCompatSlotUnderscoreLowerT, $ as pullRequestNewThreadCompatSlotDollar,
  $t as pullRequestNewThreadCompatSlotDollarLowerT, a as pullRequestNewThreadCompatSlotLowerA, A as pullRequestNewThreadCompatSlotUpperA, an as pullRequestNewThreadCompatSlotLowerALowerN,
  at as pullRequestNewThreadCompatSlotLowerALowerT, At as pullRequestNewThreadCompatSlotUpperALowerT, b as pullRequestNewThreadCompatSlotLowerB, B as pullRequestNewThreadCompatSlotUpperB,
  bn as pullRequestNewThreadCompatSlotLowerBLowerN, bt as pullRequestNewThreadCompatSlotLowerBLowerT, Bt as pullRequestNewThreadCompatSlotUpperBLowerT, c as pullRequestNewThreadCompatSlotLowerC,
  C as pullRequestNewThreadCompatSlotUpperC, cn as pullRequestNewThreadCompatSlotLowerCLowerN, ct as pullRequestNewThreadCompatSlotLowerCLowerT, Ct as pullRequestNewThreadCompatSlotUpperCLowerT,
  d as pullRequestNewThreadCompatSlotLowerD, D as pullRequestNewThreadCompatSlotUpperD, dn as pullRequestNewThreadCompatSlotLowerDLowerN, dt as pullRequestNewThreadCompatSlotLowerDLowerT,
  Dt as pullRequestNewThreadCompatSlotUpperDLowerT, E as pullRequestNewThreadCompatSlotUpperE, en as pullRequestNewThreadCompatSlotLowerELowerN, et as pullRequestNewThreadCompatSlotLowerELowerT,
  Et as pullRequestNewThreadCompatSlotUpperELowerT, f as pullRequestNewThreadCompatSlotLowerF, F as pullRequestNewThreadCompatSlotUpperF, fn as pullRequestNewThreadCompatSlotLowerFLowerN,
  ft as pullRequestNewThreadCompatSlotLowerFLowerT, Ft as pullRequestNewThreadCompatSlotUpperFLowerT, g as pullRequestNewThreadCompatSlotLowerG, G as pullRequestNewThreadCompatSlotUpperG,
  gn as pullRequestNewThreadCompatSlotLowerGLowerN, gt as pullRequestNewThreadCompatSlotLowerGLowerT, Gt as pullRequestNewThreadCompatSlotUpperGLowerT, h as pullRequestNewThreadCompatSlotLowerH,
  H as pullRequestNewThreadCompatSlotUpperH, hn as pullRequestNewThreadCompatSlotLowerHLowerN, ht as pullRequestNewThreadCompatSlotLowerHLowerT, Ht as pullRequestNewThreadCompatSlotUpperHLowerT,
  i as pullRequestNewThreadCompatSlotLowerI, I as pullRequestNewThreadCompatSlotUpperI, in as pullRequestNewThreadCompatSlotLowerILowerN, it as pullRequestNewThreadCompatSlotLowerILowerT,
  It as pullRequestNewThreadCompatSlotUpperILowerT, j as pullRequestNewThreadCompatSlotLowerJ, J as pullRequestNewThreadCompatSlotUpperJ, jt as pullRequestNewThreadCompatSlotLowerJLowerT,
  Jt as pullRequestNewThreadCompatSlotUpperJLowerT, k as pullRequestNewThreadCompatSlotLowerK, K as pullRequestNewThreadCompatSlotUpperK, kt as pullRequestNewThreadCompatSlotLowerKLowerT,
  Kt as pullRequestNewThreadCompatSlotUpperKLowerT, l as pullRequestNewThreadCompatSlotLowerL, L as pullRequestNewThreadCompatSlotUpperL, ln as pullRequestNewThreadCompatSlotLowerLLowerN,
  lt as pullRequestNewThreadCompatSlotLowerLLowerT, Lt as pullRequestNewThreadCompatSlotUpperLLowerT, m as pullRequestNewThreadCompatSlotLowerM, M as pullRequestNewThreadCompatSlotUpperM,
  mn as pullRequestNewThreadCompatSlotLowerMLowerN, mt as pullRequestNewThreadCompatSlotLowerMLowerT, Mt as pullRequestNewThreadCompatSlotUpperMLowerT, n as pullRequestNewThreadCompatSlotLowerN,
  N as pullRequestNewThreadCompatSlotUpperN, nn as pullRequestNewThreadCompatSlotLowerNLowerN, nt as pullRequestNewThreadCompatSlotLowerNLowerT, Nt as pullRequestNewThreadCompatSlotUpperNLowerT,
  o as pullRequestNewThreadCompatSlotLowerO, O as pullRequestNewThreadCompatSlotUpperO, on as pullRequestNewThreadCompatSlotLowerOLowerN, ot as pullRequestNewThreadCompatSlotLowerOLowerT,
  Ot as pullRequestNewThreadCompatSlotUpperOLowerT, p as pullRequestNewThreadCompatSlotLowerP, P as pullRequestNewThreadCompatSlotUpperP, pn as pullRequestNewThreadCompatSlotLowerPLowerN,
  pt as pullRequestNewThreadCompatSlotLowerPLowerT, Pt as pullRequestNewThreadCompatSlotUpperPLowerT, q as pullRequestNewThreadCompatSlotLowerQ, Q as pullRequestNewThreadCompatSlotUpperQ,
  qt as pullRequestNewThreadCompatSlotLowerQLowerT, Qt as pullRequestNewThreadCompatSlotUpperQLowerT, r as pullRequestNewThreadCompatSlotLowerR, R as pullRequestNewThreadCompatSlotUpperR,
  rn as pullRequestNewThreadCompatSlotLowerRLowerN, rt as pullRequestNewThreadCompatSlotLowerRLowerT, Rt as pullRequestNewThreadCompatSlotUpperRLowerT, s as pullRequestNewThreadCompatSlotLowerS,
  S as pullRequestNewThreadCompatSlotUpperS, sn as pullRequestNewThreadCompatSlotLowerSLowerN, Sn as pullRequestNewThreadCompatSlotUpperSLowerN, st as pullRequestNewThreadCompatSlotLowerSLowerT,
  St as pullRequestNewThreadCompatSlotUpperSLowerT, t as pullRequestNewThreadCompatSlotLowerT, T as pullRequestNewThreadCompatSlotUpperT, tn as pullRequestNewThreadCompatSlotLowerTLowerN,
  tt as pullRequestNewThreadCompatSlotLowerTLowerT, Tt as pullRequestNewThreadCompatSlotUpperTLowerT, u as pullRequestNewThreadCompatSlotLowerU, U as pullRequestNewThreadCompatSlotUpperU,
  un as pullRequestNewThreadCompatSlotLowerULowerN, ut as pullRequestNewThreadCompatSlotLowerULowerT, Ut as pullRequestNewThreadCompatSlotUpperULowerT, v as pullRequestNewThreadCompatSlotLowerV,
  V as pullRequestNewThreadCompatSlotUpperV, vn as pullRequestNewThreadCompatSlotLowerVLowerN, vt as pullRequestNewThreadCompatSlotLowerVLowerT, Vt as pullRequestNewThreadCompatSlotUpperVLowerT,
  w as pullRequestNewThreadCompatSlotLowerW, W as pullRequestNewThreadCompatSlotUpperW, wt as pullRequestNewThreadCompatSlotLowerWLowerT, Wt as pullRequestNewThreadCompatSlotUpperWLowerT,
  x as pullRequestNewThreadCompatSlotLowerX, X as pullRequestNewThreadCompatSlotUpperX, xn as pullRequestNewThreadCompatSlotLowerXLowerN, xt as pullRequestNewThreadCompatSlotLowerXLowerT,
  Xt as pullRequestNewThreadCompatSlotUpperXLowerT, y as pullRequestNewThreadCompatSlotLowerY, Y as pullRequestNewThreadCompatSlotUpperY, yn as pullRequestNewThreadCompatSlotLowerYLowerN,
  yt as pullRequestNewThreadCompatSlotLowerYLowerT, Yt as pullRequestNewThreadCompatSlotUpperYLowerT, z as pullRequestNewThreadCompatSlotLowerZ, Z as pullRequestNewThreadCompatSlotUpperZ,
  zt as pullRequestNewThreadCompatSlotLowerZLowerT, Zt as pullRequestNewThreadCompatSlotUpperZLowerT
} from "../../vendor/pull-request-new-thread-current-bundle";
